Revert "[code generators] Introduce explicit "useInPrefix""
This reverts commit a799a2390bc9cfab0575dca4710707424db9d0e5.

Reason for revert: Suspected to crash with:
Fatal error: Code generators must contain at least one generator to be used in the prefix

Original change's description:
> [code generators] Introduce explicit "useInPrefix"
>
> Before this CL, we chose which CodeGenerators to use in the prefix based
> on IsValueGenerator property (= all stubs in the generator require no
> inputs and produce something).
>
> However, we want to have CodeGenerators which satisfy that
> property, but which are not used in the prefix.
>
> This CL solves this problem by adding an explicit way to mark which code
> generators should be used in the prefix.
>
> CONV=fe946adb-0cf0-4d0b-a600-a45a70ecddad
> TAG=agy
> Bug: 526979176
> Change-Id: Ib5dd42efbaf082e7196992c00aa867a23c4609b0
> Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9457934
> Commit-Queue: Marja Hölttä <marja@google.com>
> Reviewed-by: Matthias Liedtke <mliedtke@google.com>

Bug: 526979176
Change-Id: I1acc51b237c4ece57cf9ef7b4637a6bd16c6ebf6
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9482515
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Michael Achenbach <machenbach@google.com>
Reviewed-by: Marja Hölttä <marja@google.com>