Add type check to PrototypeOverwriteGenerator
This patch adds a check in case an object and the object its prototype
is being set to are the same thing (i.e. obj.__proto__ = obj;)
This currently allows for an invalid program with the error:

TypeError: Cyclic __proto__ value

Bug: 40272934
Change-Id: Ib115f6f754d1cc70564bc91a5fd433033e9d5bdf
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/8557236
Reviewed-by: Matthias Liedtke <mliedtke@google.com>