[wasm] Add missing registerTypeGroupDependency() for super types
This CL adds missing calls to registerTypeGroupDependency() for
structs/arrays/signatures.

This issue flushed out when FuzzilliCli ran into
`Fuzzilli/WasmLifter.swift:564: Fatal error:
Unexpectedly found nil while unwrapping an Optional value`.

Bug: 517707090
Change-Id: I84f9aeedbfb8f5762ee113df44c3417aade15d6b
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9463675
Commit-Queue: Leon Bettscheider <bettscheider@chromium.org>
Reviewed-by: Matthias Liedtke <mliedtke@google.com>