Fix invalid code gen in configuration generators
This patch adds checks to prevent the writable property flag or value
property from being set at the same time that there are getters or
setters.
Currently, the configureProperty and configureElement generators often
generate invalid programs which raise the following exception:

TypeError: Invalid property descriptor. Cannot both specify accessors
and a value or writable attribute

This happens usually because the property flags, which include the
writable property bit (bit 0), are set to a random 8 bit integer.

Bug: 40272934
Change-Id: I3e9ce83a12c6e384064a4f430230f504d177b159
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/8543776
Commit-Queue: Hendrik Wüthrich <whendrik@google.com>
Reviewed-by: Hendrik Wüthrich <whendrik@google.com>
Reviewed-by: Matthias Liedtke <mliedtke@google.com>